### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/npm-adaptiveme-nibble#12]
When the user navigates through the emulator and clicks a html link with the tag target="_blank", the emulator does not navigate through this new window.

This behaviour is normal?

**Comment by carloslozano** [comment]
Probably not :smile: ! However, trying to open a "_blank" target would yield a new browser window in normal conditions... creation of new views are currently not allowed by Nibble.

**Comment by carloslozano** [comment]
Tracked https://github.com/AdaptiveMe/adaptive-tools-nibble/issues/4
