### ISSUE TITLE
html5test - Different results

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/npm-adaptiveme-nibble#13]
Sometimes, with the same cloned device, there are different results in http://html5test.com/

Maybe this is related with #11 because there is a message in the javascript console:

```
IndexedDB: error, could not delete database 
```

**Comment by carloslozano** [comment]
Related to #11 .

**Comment by carloslozano** [comment]
Fixed with release https://github.com/AdaptiveMe/adaptive-tools-nibble/releases/tag/1.0-alpha.4
