### ISSUE TITLE
Add new parameter to nibble: -p <start_path> -f <init_file>

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/npm-adaptiveme-nibble#15]
If you generate an application with yeoman and **bower**, by default the folder structure is the following:

```
  bower_components (libraries)
  |_ adaptiveme
    |_ adaptive.js
  src
  |_ index.html
```

The nibble web server points to the **parent folder of the index.html**, so the **bower components** are not visible for this server. I propose to create a new param that indicates the index.html file (-f) and use -p option to indicate the root folder of the web server.

**Comment by carloslozano** [comment]
The -p parameter is intended to be pointed at the dist folder/index.html (or whatever), this is after all the app as it would be distributed. If we need a "development" mode switch for the generator, then we add this.

**Comment by carloslozano** [comment]
Tracked https://github.com/AdaptiveMe/adaptive-tools-nibble/issues/7
