### ISSUE TITLE
userAgent angular demo

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/npm-adaptiveme-nibble#22]
The user agent on the angular demo application http://mobileangularui.com/demo/#/ shows an incorrent user Agent:

```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.52 Safari/537.36
```

![apple_iphone_6plus_1427465860693](https://cloud.githubusercontent.com/assets/8384895/6869452/7e4ec6cc-d494-11e4-99c7-caf5bccc0619.png)

**Comment by carloslozano** [comment]
Tracked https://github.com/AdaptiveMe/adaptive-tools-nibble/issues/6
