### ISSUE TITLE
Capture Screenshot. Issue with multiple device with different os version

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/npm-adaptiveme-nibble#23]
When I open two devices syncronized but with different os versions:

```
Iphone 6Plus iOS 8.0
Iphone 6Plus iOS 8.1
```

When I take a screenshot, there's only one screenshot. It's necessary to append the OS version to the capture ;)

**Comment by carloslozano** [comment]
Tracked https://github.com/AdaptiveMe/adaptive-tools-nibble/issues/5
