### ISSUE TITLE
Dev. Tools is not shown in windows 7 until you use the maximize option in windows taskbar app icon.

### ISSUE THREAD

**Issue by hectorrosell** [AdaptiveMe/npm-adaptiveme-nibble#32]
The first time you open the developer tools, the app is not shown in windows 7 until you use the maximize option in windows taskbar app icon.

**Comment by ferranvila** [comment]
Hello Hector, please could you open the issues related to the nibble on this repo? https://github.com/AdaptiveMe/adaptive-tools-nibble/issues

I know that the nibble points to this repo, but it's a mistake that we should correct: https://github.com/AdaptiveMe/adaptive-tools-nibble/issues/3

I just created this one for you on the other repo.

Thanks.

**Comment by ferranvila** [comment]
Moved to another repo.

**Comment by hectorrosell** [comment]
Ok, thanks.
